import type { CycleRow,Settings,Transaction } from "./types";
export const DAILY_CATEGORIES=new Set(["Ăn uống","Cafe/Giải trí","Đi lại/Xăng","Mua sắm","Khác"]);
export function money(v:number){return new Intl.NumberFormat("vi-VN",{style:"currency",currency:"VND",maximumFractionDigits:0}).format(v)}
export function shortMoney(v:number){const a=Math.abs(v);if(a>=1_000_000)return `${(v/1_000_000).toFixed(a%1_000_000===0?0:1)}tr`;if(a>=1_000)return `${Math.round(v/1_000)}k`;return String(v)}
export function localDate(d=new Date()){return new Date(d.getFullYear(),d.getMonth(),d.getDate())}
export function parseDateOnly(v:string){const [y,m,d]=v.split("-").map(Number);return new Date(y,m-1,d)}
export function toDateOnly(d:Date){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
export function addMonths(d:Date,c:number){return new Date(d.getFullYear(),d.getMonth()+c,d.getDate())}
export function cycleStartFor(date:Date,salaryDay:number,planStart:Date){const n=localDate(date);const c=n.getDate()>=salaryDay?new Date(n.getFullYear(),n.getMonth(),salaryDay):new Date(n.getFullYear(),n.getMonth()-1,salaryDay);return c<planStart?planStart:c}
export function cycleEnd(start:Date){const n=addMonths(start,1);return new Date(n.getFullYear(),n.getMonth(),n.getDate()-1)}
export function inCycle(dateStr:string,start:Date){const d=parseDateOnly(dateStr),n=addMonths(start,1);return d>=start&&d<n}
export function buildCycles(txs:Transaction[],s:Settings,through:Date,count=12):CycleRow[]{const first=parseDateOnly(s.plan_start_date);const last=cycleStartFor(through,s.salary_day,first);let cumulative=s.initial_savings;return Array.from({length:count},(_,i)=>{const start=addMonths(first,i),end=cycleEnd(start),ct=txs.filter(t=>inCycle(t.occurred_on,start)),hasData=ct.length>0;const livingBudget=s.daily_budget*30+s.rent_budget+s.incidental_budget;if(start>last&&!hasData)return{start,end,income:0,dailySpend:0,rent:0,incidental:0,livingSpend:0,livingBudget,budgetRemaining:0,debtPaid:0,totalOut:0,savings:0,cumulative,hasData:false};const income=ct.filter(t=>t.type==="Thu").reduce((a,t)=>a+t.amount,0);const dailySpend=ct.filter(t=>t.type==="Chi"&&DAILY_CATEGORIES.has(t.category)).reduce((a,t)=>a+t.amount,0);const rent=ct.filter(t=>t.type==="Chi"&&t.category==="Trọ").reduce((a,t)=>a+t.amount,0);const incidental=ct.filter(t=>t.type==="Chi"&&t.category==="Phát sinh").reduce((a,t)=>a+t.amount,0);const debtPaid=ct.filter(t=>t.type==="Chi"&&t.category==="Trả nợ").reduce((a,t)=>a+t.amount,0);const livingSpend=dailySpend+rent+incidental,budgetRemaining=livingBudget-livingSpend,totalOut=livingSpend+debtPaid,savings=income-totalOut;if(hasData)cumulative+=savings;return{start,end,income,dailySpend,rent,incidental,livingSpend,livingBudget,budgetRemaining,debtPaid,totalOut,savings,cumulative,hasData}})}
export function currentDebt(txs:Transaction[],s:Settings,through:Date){const paid=txs.filter(t=>t.type==="Chi"&&t.category==="Trả nợ"&&parseDateOnly(t.occurred_on)<=through).reduce((a,t)=>a+t.amount,0);return Math.max(0,s.starting_debt-paid)}